import localFont from "next/font/local";
import type { AppProps } from "next/app";

import "./globals.css";
import AuthContext from "./context/AuthContext";
import { StepProvider } from "@/app/context/StepContext";
import { MobileOrEmailProvider } from "@/app/context/MobileOrEmailContext";

const iranSansXV = localFont({
  src: "../public/fonts/IRANSansXV.woff",
  variable: "--font-iran-sans",
});

const iranSansNum = localFont({
  src: "../public/fonts/IRANSansWeb(FaNum).ttf",
  variable: "--font-iran-num",
});

export const metadata = {
  title: "بلیط هواپیما",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${iranSansXV.className} ${iranSansNum.className}`}>
        <AuthContext>
          <StepProvider>
            <MobileOrEmailProvider>{children}</MobileOrEmailProvider>
          </StepProvider>
        </AuthContext>
      </body>
    </html>
  );
}
